name: Challenge
version: '${project.version}'
main: com.darkvoidstudios.mcchallenges.MinecraftPlugin
description: This plugin does so much stuff it can't be contained!
author: Brok3nmind
api-version: 1.19
commands:
  challenge:
    description: Toggles the challenges